### ISSUE TITLE
Question: cleaning references and possible solution

### ISSUE THREAD

**Issue by niksy** [misteroneill/backbone-model-factory#6]
In README.md you mention:

> Note: This will only remove them from the internal cache - any references in your views, collections, or elsewhere will not be deleted!

> In the example here, all the local variables ("jake", "joe1", etc) will be garbage collected, but it's up to the developer to clean up references from his/her view, collection, etc. objects.

Do you have some suggestions on how to deal with stale references?

I was thinking something along the lines of extending `wipe` method which would trigger custom event, e.g. `cache:model:remove` which can be listened on and then developer can properly dispose of references. You could pass deleted model as argument so you can check if you’re deleting correct reference, but I’m not sure if that argument is properly garbage collected.

What do you think?

**Comment by misteroneill** [comment]
That sounds like a reasonable solution to me! Would you mind putting together a PR? I'm a bit short on free time at the moment.

**Comment by misteroneill** [comment]
Ok, I'm putting something together this weekend. Took me a while to get back to this because I started a new job in July and had a baby (well, my wife did) in August... I've been busy, to say the least. Plus, I don't use Backbone anymore in my day to day work, but I am happy to continue maintaining this project and providing patches and feature improvements as needed.

This is a useful feature request and my plan is:

- Calling `model.wipe()` will trigger `"wipe"` on that instance. The instance is passed as an argument to any callback(s).
- Calling `MyModel.wipe()` will trigger individual `"wipe"` events on every instance being wiped and...
  - If wiping all instances, trigger `"wipe:all"`.
  - If wiping fewer than all and more than zero, trigger `"wipe:some"`.
  - In both cases, callbacks receive the following arguments:
    - `Constructor`: The model constructor on which the event was triggered.
    - `models`: An array of models that were removed from the cache.
    - `remainder`: An array of models remaining in the cache.

In all cases, `{silent: true}` will be respected. Constructors returned from `Backbone.ModelFactory()` will now have all `Backbone.Events` capabilities. Finally, this is a decent-sized feature implementation, but it will remain backward-compatible; so, it will be a `1.3.0` release.

> You could pass deleted model as argument so you can check if you’re deleting correct reference, but I’m not sure if that argument is properly garbage collected.

Yes, they will be. The only way they wouldn't be garbage collected is if they were re-cached somewhere in that callback, but that's a "userland" problem - out of the scope of BMF! :smile:

**Comment by misteroneill** [comment]
One addendum to the above:

- Calling `model.wipe()` will also trigger the model/constructor-level events (`"wipe"`, `"wipe:some"`, and/or `"wipe:all"`).

**Comment by misteroneill** [comment]
This feature is now released to npm with `v1.3.0`.

@niksy I hope it works for you - thanks for the idea!

**Comment by niksy** [comment]
@misteroneill Hi, extremely sorry for not answering this earlier, been kind of busy with the current project :(

First of all, congrats on the baby and new job! :)

This implementation of feature is excellent! Thank you for providing detailed explanation of how it works and extending it with even more useful additions. Will try it on the current project I’m working on when I get the chance (I’m currently using the 1.2.0 version of module).

And thank you for maintaining the project even though you don’t use Backbone anymore! :raised_hands:

**Comment by misteroneill** [comment]
Thank you for the congratulations! 

And, regarding maintaining it, you're welcome! It's not a large project, so I don't mind tinkering with it now and then! :smile:
